### ISSUE TITLE
Fix Buffer warning

### ISSUE THREAD

**Issue by seveibar** [seamapi/nextjs-server-modules#14]
![image](https://user-images.githubusercontent.com/1910070/162498065-68186ed7-4025-483f-94bd-64b7fd8ae157.png)

**Comment by seveibar** [comment]
```
(node:127449) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:198:11)
    at new Buffer (buffer.js:282:3)
    at module2.exports (/home/seve/w/seam/sms-gate/apps/sms-gate-server/src/node_modules/iconv-lite/lib/extend-node.js:11:46)
    at node_modules/iconv-lite/lib/index.js (/home/seve/w/seam/sms-gate/apps/sms-gate-server/src/node_modules/iconv-lite/lib/index.js:143:5)
    at __require (/home/seve/w/seam/sms-gate/apps/sms-gate-server/src/run-server.ts:28:50)
    at node_modules/raw-body/index.js (/home/seve/w/seam/sms-gate/apps/sms-gate-server/src/node_modules/raw-body/index.js:17:13)
    at __require (/home/seve/w/seam/sms-gate/apps/sms-gate-server/src/run-server.ts:28:50)
    at node_modules/micro/lib/index.js (/home/seve/w/seam/sms-gate/apps/sms-gate-server/src/node_modules/micro/lib/index.js:7:20)
    at __require (/home/seve/w/seam/sms-gate/apps/sms-gate-server/src/run-server.ts:28:50)
    at Object.<anonymous> (/home/seve/w/seam/sms-gate/apps/sms-gate-server/src/.nsm/index.ts:2:19)
```

**Comment by seveibar** [comment]
It's due to `iconv-lite`. I can manually set a resolutions to fix it, but that's not great for every project that uses nextjs-server-modules
![image](https://user-images.githubusercontent.com/1910070/163502168-b3e34deb-d428-414c-aed4-c88a17ae861a.png)
